### ISSUE TITLE
Cannot find module 'pg-native' - regression pg@8.4.0

### ISSUE THREAD

**Issue by uasan** [brianc/node-postgres#2403]
Commit in version pg@8.4.0
https://github.com/brianc/node-postgres/commit/a02dfac5ad2e2abf0dc3a9817f953938acdc19b1
```JSON
"peerDependenciesMeta": {
    "pg-native": {
      "optional": true
    }
  }
```
Causes an error in projects that do not use the native PG client:
```
Cannot find module 'pg-native'
Require stack:
- .../node_modules/pg/lib/native/client.js
- .../node_modules/pg/lib/native/index.js
- .../node_modules/pg/lib/index.js
```
How do I fix this error?

**Comment by saleh-rahimzadeh** [comment]
I get this error when I use 'pg' as ECMAScript module.

package.json:
`{
"type": "module"
}`

index.js:
`import pg from 'pg'`

**Comment by uasan** [comment]
> I get this error when I use 'pg' as ECMAScript module.

Yes, this my case.

> I got this error after updating node.js from 14.9.0 to 14.15.0.

I think it depends on the version of the npm

**Comment by charmander** [comment]
Pretty sure this wasn’t caused by that change and isn’t a regression.

**Comment by charmander** [comment]
Duplicate of #2387
