### ISSUE TITLE
[v8.15.0] Regression: UnhandledSchemeError "cloudflare:sockets" when bundling with Webpack

### ISSUE THREAD

**Issue by andrew-pledge-io** [brianc/node-postgres#3452]
After upgrading to 8.15.0, bundling with Webpack results in the following error:

```
Webpack compilation failed:
in cloudflare:sockets
  Module build failed: UnhandledSchemeError: Reading from "cloudflare:sockets" is not handled by plugins (Unhandled scheme).
  Webpack supports "data:" and "file:" URIs by default.
  You may need an additional plugin to handle "cloudflare:" URIs.
```

This previously occurred in version 8.11.0: https://github.com/brianc/node-postgres/issues/2975

And was fixed in this PR: https://github.com/brianc/node-postgres/pull/2978

**Comment by CHC383** [comment]
As noted in #2978, the temporary workarounds would be:

**webpack.config.js**
```js
  plugins: [
    new webpack.IgnorePlugin({
      resourceRegExp: /^cloudflare:sockets$/,
    }),
  ],
```

**next.config.ts**
```js
  webpack: (config, { webpack }) => {
    config.plugins.push(
      new webpack.IgnorePlugin({
        resourceRegExp: /^cloudflare:sockets$/,
      }),
    );
    return config;
  },
```

**Comment by brianc** [comment]
hmmm thanks for the info! Any idea on the right fix here? I wonder if I should write a test by trying to webpackify everything in a separate module in the repo & see if it works?

**Comment by CHC383** [comment]
@brianc If you are okay with the conditional exports as the previous version, how about using [nested conditions](https://nodejs.org/docs/latest-v22.x/api/packages.html#nested-conditions)? Something like:
```json
  "exports": {
    ".": {
      "cloudflare": {
        "import": "./esm/index.mjs",
        "require": "./dist/index.js",
      }
      "default": "./dist/index.js"
    }
  },
```
And users of Cloudflare Workers need to explicitly enable the conditions in their webpack configs.

Or another option might be move/remove the dependency `pg-cloudflare`, and users need to explicitly add it as a dependency in their `package.json`.

**Comment by cjnoname** [comment]
We're experiencing the same issue. Is there a better solution for this?

**Comment by willr42** [comment]
Also experiencing this. Is there a workaround for Vite?

**Comment by brianc** [comment]
I'm open to a PR to fix this....particularly if there's a test included to reproduce it, though that's not required.

**Comment by josuazurbruegg** [comment]
> Also having the same regession with vite. The last working resolved version is `pg-cloudflare@1.1.1`. Any version after this breaks my build. I also cant figure out how to force pnpm to resolve to this version for `pg` package dependencies. I have to manually go into my `pnpm-lock.yaml` file and revert back to the `1.1.1` resolution any time I make dependency updates.

I was struggling with this for a bit today as well. It seems pnpm overrides dependencies at the root level in a monorepo (makes sense, I guess) and overrides needs to be specified differently. Both of the following worked for me:

In pnpm-workspace.yaml:
`
overrides:
  pg-cloudflare: 1.1.1
`

and in root package.json:
`
"pnpm": {
    "overrides": {
      "pg-cloudflare": "1.1.1"
    }
  },
`

**Comment by CHC383** [comment]
While waiting for #3482, if you need a temporary workaround to allow/ignore `cloudflare:sockets` for `webpack`/`vite`/`rollup` instead of reverting pg-cloudflare to `1.1.1`, please check the tests or README in #3482.

Basically the configs to handle `cloudflare:sockets` would be needed whenever `pg-cloudflare` is enabled while using some bundlers. Right now `pg-cloudflare` is enabled by default, and after #3482 it will be enabled through resolve conditions.
