### ISSUE TITLE
node 0.9.2 compatibility

### ISSUE THREAD

**Issue by sdepold** [brianc/node-postgres#222]
Seems that node-postgres is broken when used with node 0.9.

``` javascript
require('pg').native
Error: Cannot find module '/Users/sdepold/Projects/sequelize/node_modules/pg/lib/native/../../build/default/binding'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/sdepold/Projects/sequelize/node_modules/pg/lib/native/index.js:12:12)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```

require('pg') is working without any issues. also everything is working with the latest 0.8 release
